[workspace]
resolver = "3"
members = [
    "lumina-desktop",
    "lumina-core",
    "lumina-shared",
    "lumina-skia-renderer",
    "lumina-ui",
    "viviscript-core"
]

[profile.bench]
debug = true
