[package]
name = "lumina-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
anyhow = "1.0.100"
log = "0.4.29"
once_cell = "1.21.3"